<?php
/*
 * Synapse Registration form
 * @author Cameron Milton <cameron@anat.org.au>
 */

/**
 * parses a feed into a basic html list
 * @todo: prevent going over end of item array with validation.
 * dynamically generate form to add more feeds.
 */

 /* variable_get('id') */

//hooks
/**
 * Implements admin().
 */
function SynapseRegister_admin() {
    //solve360key
    $form['SynapseRegister_solve360key'] = array (
        '#type' => 'textfield',
        '#title' => t('solve360 api key'),
        '#default_value' => variable_get('SynapseRegister_solve360key', ''),
        '#description' => t("Solve360 API key"),
        '#required' => TRUE,
    );
    $form['SynapseRegister_mailchimpkey'] = array(
		'#type' => 'textfield',
        '#title' => t('MailChimp api key'),
		'#default_value' => variable_get('SynapseRegister_mailchimpkey', ''),
		'#description' => t("MailChimp API Key"),
		'#required' => TRUE,
	);
    return system_settings_form($form);
}

/**
 * Implements menu().
*/
function SynapseRegister_menu() {
    $items['admin/config/registration'] = array(
        'title' => 'Registration Form',
        'description' => 'Set options for the registration form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('SynapseRegister_admin'),
        'access arguments' => array('administer permissions'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}
/**/
//end of admin
?>
